# Generated by Django 5.2.7 on 2025-10-27 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 11, 9)),
        ),
    ]
